// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDM4R2a0-0NmVPCjFSL_nIsJfSEZbL-uA',
    appId: '1:570926038088:web:b8a12b50281fa2575dec7d',
    messagingSenderId: '570926038088',
    projectId: 'st-project-7605b',
    authDomain: 'st-project-7605b.firebaseapp.com',
    storageBucket: 'st-project-7605b.firebasestorage.app',
    measurementId: 'G-9603LJ8QZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxB3w-fJahhMJjtyFFYrSLbbRCxSFs_k',
    appId: '1:570926038088:android:162b91e3fefb28575dec7d',
    messagingSenderId: '570926038088',
    projectId: 'st-project-7605b',
    storageBucket: 'st-project-7605b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByeZ3wbM5DrxdYDsVb71ahMZeluC4LyOc',
    appId: '1:570926038088:ios:7a1d39832ec0a86d5dec7d',
    messagingSenderId: '570926038088',
    projectId: 'st-project-7605b',
    storageBucket: 'st-project-7605b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
